apiVersion: v1
kind: Service
metadata:
  name: my-smclone-app
spec:
  type: LoadBalancer 
  selector:
    app: my-smclone-app
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080 
